require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - vendor/**/*
    - .vendor/**/*
    - spec/fixtures/site/vendor/**/*
    - spec/fixtures/site/.cache/**/*

# Disable Layout/BlockAlignment cop due to crashes with current RuboCop version
# See: https://github.com/rubocop-hq/rubocop/issues
Layout/BlockAlignment:
  Enabled: false
