require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  inherit_mode:
    merge:
      - Exclude
  Exclude:
    - "*.gemspec"

# Disable Layout/BlockAlignment cop due to crashes with current RuboCop version
# See: https://github.com/rubocop-hq/rubocop/issues
Layout/BlockAlignment:
  Enabled: false
